Composition {
	CurrentTime = 20,
	RenderRange = { 0, 150 },
	GlobalRange = { 0, 150 },
	CurrentID = 139,
	HiQ = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 16.1.1 build 5",
	SavedOutputs = 2,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		TimeMachine2 = Fuse.TimeMachineImage {
			Inputs = {
				ImageInput = Input {
					SourceOp = "Crop1",
					Source = "Output",
				},
				Mode = Input { Value = FuID { "LockStart" }, },
				Skip = Input { Value = 1, },
				XFrameNumbers = Input { Disabled = true, },
				TargetStartFrame = Input { Expression = "Controls.NumberIn3", },
			},
			ViewInfo = OperatorInfo { Pos = { 450.988, 117.061 } },
			Version = 211
		},
		Transform1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.5, 0.777472527472527 }, },
				Size = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "TimeMachine2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 615.214, 117.061 } },
		},
		Transform2 = Transform {
			Inputs = {
				Input = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 801.425, -72.4079 } },
		},
		Merge2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Transform1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform2",
					Source = "Output",
				},
				Center = Input { Value = { 0.1707882534776, 0.7967032967033 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 801.425, 117.061 } },
		},
		Transform1_1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.5, 0.255494505494505 }, },
				Size = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "Crop1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 611.724, 186.758 } },
		},
		Transform3 = Transform {
			Inputs = {
				Center = Input { Value = { 0.1707882534776, 0.263736263736264 }, },
				Input = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 801.863, -19.9719 } },
		},
		Merge3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Transform1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform3",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 801.863, 186.758 } },
		},
		TimeMachine1 = Fuse.TimeMachineImage {
			Inputs = {
				ImageInput = Input {
					SourceOp = "Merge3",
					Source = "Output",
				},
				Mode = Input { Value = FuID { "LockStart" }, },
				Skip = Input { Value = 1, },
				XFrameNumbers = Input { Disabled = true, },
				TargetStartFrame = Input {
					Value = 20,
					Expression = "Controls.NumberIn1+Controls.NumberIn2",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1090.71, 186.758 } },
			Version = 211
		},
		PipeRouter1 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "TimeMachine1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1546.06, 186.758 } },
		},
		Merge1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "PipeRouter1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1546.06, 117.061 } },
		},
		Background2_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 150, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -157.58, 117.061 } },
		},
		Transform4 = Transform {
			Inputs = {
				Center = Input {
					SourceOp = "Path1",
					Source = "Position",
				},
				Size = Input { Value = 2.14, },
				Angle = Input { Value = 78.3, },
				Input = Input {
					SourceOp = "Background2_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -5.81807, 117.061 } },
		},
		Path1 = PolyPath {
			DrawMode = "InsertAndModify",
			CtrlWZoom = false,
			Inputs = {
				Displacement = Input {
					SourceOp = "Path1Displacement",
					Source = "Value",
				},
				PolyLine = Input {
					Value = Polyline {
						Points = {
							{ Linear = true, LockY = true, X = -1.18735891647856, Y = 0, RX = 0.391271632806622, RY = 0 },
							{ Linear = true, LockY = true, X = -0.0135440180586908, Y = 0, LX = -0.391271632806622, LY = 0 }
						}
					},
				},
			},
		},
		Path1Displacement = BezierSpline {
			SplineColor = { Red = 255, Green = 0, Blue = 255 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, RH = { 6.66666666666667, 0 }, Flags = { LockedY = true } },
				[20] = { 1, LH = { 13.3333333333333, 1 }, Flags = { LockedY = true } }
			}
		},
		Crop1 = Crop {
			Inputs = {
				XSize = Input { Value = 1920, },
				YSize = Input { Value = 1080, },
				Input = Input {
					SourceOp = "Transform4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 236.864, 117.061 } },
		},
		Transform1_1_1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.815254237288136, 0.255494505494505 }, },
				Size = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "Crop1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 608.48, 264.14 } },
		},
		Text1 = TextPlus {
			Inputs = {
				GlobalOut = Input { Value = 150, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				StyledText = Input {
					Value = "143",
					Expression = "Text(time)",
				},
				Font = Input { Value = "Open Sans", },
				Style = Input { Value = "Bold", },
				Size = Input { Value = 0.04562, },
				VerticalJustificationNew = Input { Value = 3, },
				HorizontalJustificationNew = Input { Value = 3, },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 801.863, -135.089 } },
		},
		Transform3_1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.820505767601894, 0.528796504700119 }, },
				Input = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 801.813, 27.5736 } },
		},
		Merge5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Transform1_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform3_1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 801.813, 264.14 } },
		},
		TimeMachine1_1 = Fuse.TimeMachineImage {
			Inputs = {
				ImageInput = Input {
					SourceOp = "Merge5",
					Source = "Output",
				},
				Mode = Input { Value = FuID { "LockStart" }, },
				Skip = Input { Value = 1, },
				XFrameNumbers = Input { Disabled = true, },
				TargetStartFrame = Input {
					Value = 40,
					Expression = "Controls.NumberIn1*2+Controls.NumberIn2*2",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1088.48, 264.14 } },
			Version = 211
		},
		PipeRouter2 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "TimeMachine1_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1708.3, 264.14 } },
		},
		Merge6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "PipeRouter2",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1708.3, 117.061 } },
		},
		Controls = Custom {
			CtrlWZoom = false,
			Inputs = {
				NumberIn1 = Input { Value = 20, },
				LUTIn1 = Input {
					SourceOp = "CustomTool1LUTIn1",
					Source = "Value",
				},
				LUTIn2 = Input {
					SourceOp = "CustomTool1LUTIn2",
					Source = "Value",
				},
				LUTIn3 = Input {
					SourceOp = "CustomTool1LUTIn3",
					Source = "Value",
				},
				LUTIn4 = Input {
					SourceOp = "CustomTool1LUTIn4",
					Source = "Value",
				},
				AuxChannelNest = Input { Value = 1, },
				NumberControls = Input { Value = 1, },
				NameforNumber1 = Input { Value = "Time Offset", },
				NameforNumber2 = Input { Value = "Space Between Anim", },
				NameforNumber3 = Input { Value = "Start Animation", },
				ShowNumber4 = Input { Value = 0, },
				ShowNumber5 = Input { Value = 0, },
				ShowNumber6 = Input { Value = 0, },
				ShowNumber7 = Input { Value = 0, },
				ShowNumber8 = Input { Value = 0, },
				ShowPoint1 = Input { Value = 0, },
				ShowPoint2 = Input { Value = 0, },
				ShowPoint3 = Input { Value = 0, },
				ShowPoint4 = Input { Value = 0, },
				ShowLUT1 = Input { Value = 0, },
				ShowLUT2 = Input { Value = 0, },
				ShowLUT3 = Input { Value = 0, },
				ShowLUT4 = Input { Value = 0, },
				Image1 = Input {
					SourceOp = "Merge6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1853.35, 117.061 } },
		},
		CustomTool1LUTIn1 = LUTBezier {
			KeyColorSplines = {
				[0] = {
					[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
					[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
				}
			},
			SplineColor = { Red = 204, Green = 0, Blue = 0 },
			NameSet = true,
		},
		CustomTool1LUTIn2 = LUTBezier {
			KeyColorSplines = {
				[0] = {
					[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
					[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
				}
			},
			SplineColor = { Red = 0, Green = 204, Blue = 0 },
			NameSet = true,
		},
		CustomTool1LUTIn3 = LUTBezier {
			KeyColorSplines = {
				[0] = {
					[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
					[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
				}
			},
			SplineColor = { Red = 0, Green = 0, Blue = 204 },
			NameSet = true,
		},
		CustomTool1LUTIn4 = LUTBezier {
			KeyColorSplines = {
				[0] = {
					[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
					[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
				}
			},
			SplineColor = { Red = 204, Green = 204, Blue = 204 },
			NameSet = true,
		}
	},
	Frames = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 1920,
			Height = 984,
			ZoneInfo = {
				AuxRight = { Expanded = true },
				["!Left"] = {
				},
				AuxLeft = { Expanded = true },
				Right = { Expanded = true, },
				Left = { Expanded = false, },
				["!Right"] = {
				}
			},
			ViewInfo = {
				Viewer1 = { Show = true, RatioY = 1, RatioX = 0.671122994652406, },
				InnerLeft = {
				},
				MainSplit = {
					RatioX = 1,
					RatioY = 0.358050847457627,
				},
				CenterSplit = {
					RatioX = 0.780907668231612,
					RatioY = 1,
				},
				Viewer2 = { Show = true, RatioY = 1, RatioX = 0.328877005347594, },
				Comments = { Show = false },
				Time = { Show = true, RatioX = 1, PixelY = 83, },
				InnerColumns = {
					RatioX = 1,
					RatioY = 0.641949152542373,
				},
				Keyframes = { Show = false, Adjust = true, RatioY = 1, MRU = 0, RatioX = 0.5, },
				LayoutStrip = { Show = true, RatioX = 1, },
				Inspector = { Show = true, RatioY = 1, RatioX = 1, },
				InnerRight = {
				},
				MediaPool = { Show = false, },
				OuterColumns = {
					RatioX = 1,
					RatioY = 0.963302752293578,
				},
				Effects = { Show = false, },
				ActionStrip = { Show = false, },
				Metadata = { Show = false, },
				OuterLeft = {
				},
				ViewerSplit = {
					RatioX = 1,
					RatioY = 0.862809917355372,
				},
				Nodes = { Show = true, RatioY = 1, RatioX = 1, },
				OuterRight = {
					PixelX = 420,
					RatioY = 1,
				},
				Clips = { Show = false, },
				Spline = { Show = false, Adjust = true, RatioY = 1, MRU = 0, RatioX = 0.5, }
			},
			Views = ordered() {
				Effects = MultiView {
					Active = "EffectView",
					ViewList = ordered() {
						EffectView = "EffectView"
					},
				},
				Nodes = MultiView {
					Active = "FlowView",
					ViewList = ordered() {
						FlowView = "FlowView"
					},
					Names = {
						FlowView = "FlowView"
					},
					FlowView = FlowView {
						Flags = {
							AutoHideNavigator = true,
							ConnectedSnap = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.5,
						Offset = { 0, 0 }
					}
				},
				Keyframes = MultiView {
					Active = "TimelineView",
					ViewList = ordered() {
						TimelineView = "TimelineView"
					},
					Names = {
						TimelineView = "TimelineView"
					},
					TimelineView = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 232, Bottom = 320 },
							ScaleX = 0.321637426900585,
							OffsetX = -7.39766081871345,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 232, Visible = false }
					}
				},
				Spline = MultiView {
					Active = "SplineView",
					ViewList = ordered() {
						SplineView = "SplineEditorView"
					},
					Names = {
						SplineView = "SplineView"
					},
					SplineView = SplineEditorView {
						LeftPos = 264,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -3.4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					}
				},
				Inspector = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Viewer1 = MultiView {
					Active = "LeftView",
					ViewList = ordered() {
						LeftView = "PreviewContainer"
					},
					Names = {
						LeftView = "LeftView"
					},
				},
				Viewer2 = MultiView {
					Active = "RightView",
					ViewList = ordered() {
						RightView = "PreviewContainer"
					},
					Names = {
						RightView = "RightView"
					},
				},
				Time = "TimeView",
				ActionStrip = "ActionStripView",
				LayoutStrip = "LayoutStripView"
			},
			Layout = {
				Rows = 2,
				RatioX = 1,
				RatioY = 1,
				{ ID = "LayoutStrip", RatioX = 1, FixedY = 36, Flat = true },
				{
					Columns = 2,
					RatioY = 0.963302752293578,
					{
						Rows = 2,
						RatioX = 0.780907668231612,
						RatioY = 1,
						{
							Rows = 2,
							RatioX = 1,
							RatioY = 1,
							{
								Columns = 2,
								RatioX = 1,
								RatioY = 0.862809917355372,
								{ ID = "Viewer1", RatioX = 0.671122994652406, RatioY = 1 },
								{ ID = "Viewer2", RatioX = 0.328877005347594 }
							},
							{ ID = "Time", FixedY = 83, Flat = true }
						},
						{ ID = "Nodes", RatioX = 1, RatioY = 1 }
					},
					{ ID = "Inspector", RatioX = 1, RatioY = 1 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Auto = true
				},
			},
			Views = {
				Right = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "GamutViewLUT",
						ScaleMode = 1,
						LUTSelected = "Gamut View LUT"
					},
					SubView = {
						Enabled = true,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLHistogramViewer = {
							AutoBounds = true
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT1 = ViewOperator {
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" } },
										DoAlpha = Input { Value = 1 }
									},
									CtrlWZoom = false
								}
							},
							ID = "GamutViewLUT"
						},
						Recent = {
							SelectedPlugin = "GamutViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										},
										CtrlWZoom = false
									}
								}
							},
							SelectedName = "Gamut View LUT"
						},
						SelectedName = "Gamut View LUT",
						SelectedPlugin = "GamutViewLUT"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					Toolbar = {
						Style = 0,
						Size = 0
					},
					OpToolbar = {
						Style = 0,
						Size = 1
					}
				},
				Left = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "GamutViewLUT",
						ScaleMode = 1,
						LUTSelected = "Gamut View LUT"
					},
					SubView = {
						Enabled = true,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLHistogramViewer = {
							AutoBounds = true
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT = ViewOperator {
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" } },
										DoAlpha = Input { Value = 1 }
									},
									CtrlWZoom = false
								}
							},
							ID = "GamutViewLUT"
						},
						Recent = {
							SelectedPlugin = "GamutViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "Gamut View LUT"
						},
						SelectedName = "Gamut View LUT",
						SelectedPlugin = "GamutViewLUT"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					Toolbar = {
						Style = 0,
						Size = 0
					},
					OpToolbar = {
						Style = 0,
						Size = 1
					}
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 1,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					PickH = 1,
					PrevCtrlActiveColor = 0,
					AlwaysOnTop = true,
					FullScreen = false
				},
				Defaults = {
					OpToolbar = {
						Size = 1
					},
				},
				RightView = {
					SubView = {
						Enabled = false,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLColorInspector = {
							AutoBounds = true
						},
						GLHistogramViewer = {
							AutoBounds = true
						}
					},
					PickW = 1,
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT1 = ViewOperator {
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" } },
										DoAlpha = Input { Value = 1 }
									},
									CtrlWZoom = false
								}
							},
							ID = "GamutViewLUT"
						},
						SelectedPlugin = "GamutViewLUT",
						SelectedName = "Gamut View LUT"
					},
					PickH = 1,
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "GamutViewLUT",
						LUTSelected = "Gamut View LUT",
						CheckerUnderlay = false,
						ScaleMode = 1
					},
					Toolbar = {
						Style = 0,
						Size = 0
					},
					OpToolbar = {
						Style = 0,
						Size = 0
					},
				},
				View2 = {
					PickH = 1,
					PickW = 1,
					AlwaysOnTop = true,
					FullScreen = false
				},
				LeftView = {
					SubView = {
						Enabled = false,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLColorInspector = {
							AutoBounds = true
						},
						GLHistogramViewer = {
							AutoBounds = true
						}
					},
					PickW = 1,
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT = ViewOperator {
									CtrlWZoom = false,
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" }, },
										DoAlpha = Input { Value = 1, },
									},
								}
							},
							ID = "GamutViewLUT"
						},
						Recent = {
							SelectedPlugin = "GamutViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "Gamut View LUT"
						},
						SelectedName = "Gamut View LUT",
						SelectedPlugin = "GamutViewLUT"
					},
					PickH = 1,
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "GamutViewLUT",
						LUTSelected = "Gamut View LUT",
						CheckerUnderlay = false,
						ScaleMode = 1,
						Channel = 4294967295,
					},
					Toolbar = {
						Style = 0,
						Size = 0
					},
					OpToolbar = {
						Style = 0,
						Size = 0
					},
				}
			},
			Preview = {
				HiQ = false,
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			LastFile = "Y:\\My Drive\\Dyne - Works\\Canda Dry - FAXXI '19\\07_Render\\02_PreRender\\02_Animation\\CD_Anim_Coolnic_Scn 010\\CD_Anim_Coolnic_Scn 010_MainPreRenderBG-v02.mov",
			Unsorted = {
				GlobalEnd = 150,
				RenderSettings = {
					Configs = {
					}
				}
			},
			Tweaks = {
				OpenCL = {
					Enable = 1,
					Caching = 2
				}
			},
			Paths = {
			},
			FlowView = {
				ConnectedSnap = true,
			},
			QuickTime = {
			},
		}
	},
}

 